### ISSUE TITLE
linux mint 19 下破坏依赖～

### ISSUE THREAD

**Issue by zuohuadong** [Jactor-Sue/Deepin-Apps-Installation#1]
希望增加 linux mint 19 的支持

**Comment by zuohuadong** [comment]
删除 /usr/share/doc/libreadline7/changelog.Debian.gz

![default](https://user-images.githubusercontent.com/11203929/41188646-62bf6660-6bf3-11e8-8f10-5373cdb0b630.png)

![default](https://user-images.githubusercontent.com/11203929/41188649-6d357896-6bf3-11e8-8c2d-0feeca3c0124.png)

**Comment by zuohuadong** [comment]
依次处理下来，算是装上了～～  测试下 QQ

**Comment by zuohuadong** [comment]
依次处理下来，算是装上了～～  测试下 QQ 可以了
我之前 linux mint  16.04 的安装脚本。

```
#/bin/sh
sudo apt-get install lib32z1 lib32ncurses5 p7zip p7zip-full libp11-kit0:i386 libxt6:i386 ocl-icd-libopencl1:i386 odbcinst:i386 odbcinst1debian2:i386 p11-kit-modules:i386 unixodbc:i386 libp11-kit-gnome-keyring:i386
sudo dpkg -i deepin-wine-helper-d/*.deb
sudo dpkg -i deepin-wine-d/*.deb
sudo dpkg -i qq-d/*.deb
sudo dpkg -i deepin.com.qq.office_1.0.4deepin4_i386.deb
sudo rm -rf /usr/share/doc/libgstreamer-plugins-base0.10-0/changelog.Debian.gz
sudo rm -rf /usr/share/doc/libgstreamer0.10-0/changelog.Debian.gz
sudo apt-get install -f
sudo ldconfig
```

**Comment by Jactor-Sue** [comment]
我特意去下载了一个LM19的包，在虚拟机里面测试了一下，按照教程可以用，中间会出现错误，但是按照前面提到的方式可以解决

**Comment by zuohuadong** [comment]
恩，最终解决了，我写了一个 脚本，已经提交 PR了

**Comment by Jactor-Sue** [comment]
你这个脚本不通用，不能Merge

**Comment by zuohuadong** [comment]
针对不同系统写不同脚本就行了～  做个判断。


当然，我觉得 snapd 和 flatpak  还是最好的解决方案～

**Comment by zuohuadong** [comment]
不知道有没有打包的计划。

如果没的话，我暂时先 Fork 一份，弄个小白脚本～
