### ISSUE TITLE
依赖旧版本

### ISSUE THREAD

**Issue by da1234cao** [Jactor-Sue/Deepin-Apps-Installation#19]
dpkg: 处理软件包 libpng16-16:i386 (--install)时出错：
 现在尚不能配置软件包 libpng16-16:i386 1.6.34-1，因为 libpng16-16:amd64 处于一个不同的版本(1.6.34-1ubuntu0.18.04.2)
dpkg: 处理软件包 libpng16-16:amd64 (--install)时出错：
 现在尚不能配置软件包 libpng16-16:amd64 1.6.34-1ubuntu0.18.04.2，因为 libpng16-16:i386 处于一个不同的版本(1.6.34-1)
dpkg: 处理软件包 libreadline7:i386 (--install)时出错：
 现在尚不能配置软件包 libreadline7:i386 7.0-1，因为 libreadline7:amd64 处于一个不同的版本(7.0-3)
dpkg: 处理软件包 libreadline7:amd64 (--install)时出错：
 现在尚不能配置软件包 libreadline7:amd64 7.0-3，因为 libreadline7:i386 处于一个不同的版本(7.0-1)

**Comment by Jactor-Sue** [comment]
请参考 FAQ 中 [安装时错误处理方法](https://github.com/Jactor-Sue/Deepin-Apps-Installation/blob/master/docs/FAQs.md#%E5%AE%89%E8%A3%85%E8%BF%87%E7%A8%8B%E4%B8%AD%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
