### ISSUE TITLE
增加 自动安装脚本或打包成 snap 应用

### ISSUE THREAD

**Issue by zuohuadong** [Jactor-Sue/Deepin-Apps-Installation#2]
减少环境依赖问题～～

**Comment by Jactor-Sue** [comment]
因为安装过程中可能会出现错误，需要逐步排查，写成脚本形式不利于此

**Comment by zuohuadong** [comment]
snap  或者 flatpak 包自带了环境，不依赖任何外部环境，本身相当于一个容器，所以不会出错。

**Comment by kt1024** [comment]
appimage考虑下?

**Comment by Jactor-Sue** [comment]
基于容器/沙盒类的暂时不考虑了，QQ、TIM已经有人用appimage做好了，[Wine-QQ-TIM](https://github.com/askme765cs/Wine-QQ-TIM)。迅雷、百度网盘这种的话，下载大东西的话可能会有问题吧。我现在再考虑将环境封装成一个deb包。

**Comment by zuohuadong** [comment]
@Jactor-Sue  下载地址我可以解决～
Wine-QQ-TIM 打包的不是深度的，也没有断线重连这些。
deb 包还是有环境问题，而且不支持 redhat 系
