### ISSUE TITLE
可以考虑添加qq音乐

### ISSUE THREAD

**Issue by Sciroccogti** [Jactor-Sue/Deepin-Apps-Installation#30]
作者仓库：[QQMusic](https://github.com/gorquan/QQMusic)，该文件暂时未在deepin官方源找到。

不过在Ubuntu 18.04上存在严重的乱码问题：
![图片](https://user-images.githubusercontent.com/32357397/73594671-6bb35500-454b-11ea-8f86-c8ad52587670.png)

**Comment by Hoking007** [comment]
可以用winetricks-zh安装QQ音乐，亲测可用，中文正常无乱码

**Comment by Sciroccogti** [comment]
已有官方 Linux 版
