### ISSUE TITLE
关于 QQ 的一些备注，希望能放到首页

### ISSUE THREAD

**Issue by Menci** [Jactor-Sue/Deepin-Apps-Installation#5]
换用 phpcj 的 wineqq 里的 QQ，可以拥有去广告、防撤回等功能。phpcj.org/wineqq
调用 winecfg 将 Windows 版本改为 Windows 10（Windows Vista 以上就可以），可以去掉烦人的黑边框并且拥有阴影效果

**Comment by Jactor-Sue** [comment]
Deepin 移植的QQ和TIM比phpcj的好用
