### ISSUE TITLE
Error: Dependency is not satisfialbe: deepin-win32-preloader 

### ISSUE THREAD

**Issue by Chongyao** [Jactor-Sue/Deepin-Apps-Installation#7]
My system is Linux Mint 18.2 Chinnaon 64-bit.  I followed the steps.  When I open the app's installer(.deb), I got the mistake.

**Comment by Jactor-Sue** [comment]
Probably because of the errors in step 4. Try to install each package in order dependently, and deal with the errors described above.

很可能是因为在第四步出问题了，可以试试按顺序依次安装每个包（不是一次安装所有的包），然后再按照报的错误处理问题。

**Comment by Jactor-Sue** [comment]
I installed both without conflict, show me the output when you install it.

**Comment by Chongyao** [comment]
I Download i386 version and try to install it.   
$ sudo dpkg -i libgtk2.0-0_2.24.31-2_i386.deb
(Reading database ... 456123 files and directories currently installed.)
Preparing to unpack libgtk2.0-0_2.24.31-2_i386.deb ...
Unpacking libgtk2.0-0:i386 (2.24.31-2) over (2.24.31-2) ...
dpkg: error processing package libgtk2.0-0:i386 (--install):
 package libgtk2.0-0:i386 2.24.31-2 cannot be configured because libgtk2.0-0:amd64 is at a different version (2.24.30-1ubuntu1.16.04.2)
Processing triggers for libc-bin (2.23-0ubuntu10) ...
Errors were encountered while processing:
 libgtk2.0-0:i386
$sudo apt install -f 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Correcting dependencies... Done
The following packages will be REMOVED:
  libgtk2.0-0:i386
0 upgraded, 0 newly installed, 1 to remove and 34 not upgraded.
2 not fully installed or removed.
After this operation, 6,557 kB disk space will be freed.
Do you want to continue? [Y/n] y
(Reading database ... 456122 files and directories currently installed.)
Removing libgtk2.0-0:i386 (2.24.31-2) ...
Processing triggers for libc-bin (2.23-0ubuntu10) ...
Setting up libgtk2.0-0:amd64 (2.24.30-1ubuntu1.16.04.2) ...
Processing triggers for libc-bin (2.23-0ubuntu10) ...

**Comment by Jactor-Sue** [comment]
Try this `sudo apt install libgtk2.0-0`, and the output.

**Comment by Chongyao** [comment]
sudo apt install libgtk2.0-0  
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libgtk2.0-0 is already the newest version (2.24.30-1ubuntu1.16.04.2).
0 upgraded, 0 newly installed, 0 to remove and 34 not upgraded.

**Comment by Jactor-Sue** [comment]
It should be work now, try the tutorial again.

**Comment by Chongyao** [comment]
I followed the steps before and inferred that the the reason is the i386 version of the libgtk2.0-0, which wasn't  listed in the apt sources.  So I tried to install it manually but failed because of version conflict.


$ sudo dpkg -i 6.1\ deepin-wine-plugin_1.0deepin2_i386.deb
(Reading database ... 456098 files and directories currently installed.)
Preparing to unpack 6.1 deepin-wine-plugin_1.0deepin2_i386.deb ...
Unpacking deepin-wine-plugin:i386 (1.0deepin2) over (1.0deepin2) ...
dpkg: dependency problems prevent configuration of deepin-wine-plugin:i386:
 deepin-wine-plugin:i386 depends on libgtk2.0-0; however:
  Package libgtk2.0-0:i386 is not installed.

dpkg: error processing package deepin-wine-plugin:i386 (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 deepin-wine-plugin:i386
 $sudo apt install -f 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Correcting dependencies... Done
The following packages will be REMOVED:
  deepin-wine-plugin:i386
0 upgraded, 0 newly installed, 1 to remove and 34 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
(Reading database ... 456097 files and directories currently installed.)
Removing deepin-wine-plugin:i386 (1.0deepin2) ...

**Comment by Jactor-Sue** [comment]
It shows missing package `libgkt2.0-0:i386`, so install it by `sudo apt install libgtk2.0-0:i386`, and try it agin .
