### ISSUE TITLE
在 Ubuntu 18.04 下，TIM 收到消息后窗口会跳到前台

### ISSUE THREAD

**Issue by Menci** [Jactor-Sue/Deepin-Apps-Installation#8]

**Comment by Jactor-Sue** [comment]
这个目前在Gnome桌面下无解，我尝试过通过禁止StealFocus来阻止弹出，但是这会引起其他问题，所以推荐你随时关闭聊天窗口，然后通过[快捷键](https://github.com/Jactor-Sue/Deepin-Apps-Installation/blob/master/docs/FAQs.md#%E5%BE%AE%E4%BF%A1qq%E5%BF%AB%E6%8D%B7%E9%94%AE)来调出窗口。

**Comment by Menci** [comment]
旧版的 gnome 好像没有这个问题？我换 dde 吧 … 谢谢

**Comment by tydlwav** [comment]
建议放到FAQ里，这个是非常annoying并且常见的问题（Cinnamon也会遇到）
