### ISSUE TITLE
安装错误

### ISSUE THREAD

**Issue by xwjBupt** [Jactor-Sue/Deepin-Apps-Installation#9]
ubuntu 14.04 运行install_wine.sh完成但是安装软件提示依赖没有安装
`xwj@LAB:/media/xwj/File/software/Deepin-Apps-Installation$ sudo sh ./install-deepin-wine.sh 
updating cache
忽略 http://mirrors.tuna.tsinghua.edu.cn trusty InRelease
命中 http://mirrors.tuna.tsinghua.edu.cn trusty-updates InRelease              
命中 http://mirrors.tuna.tsinghua.edu.cn trusty-backports InRelease            
命中 http://mirrors.tuna.tsinghua.edu.cn trusty-security InRelease             
命中 http://mirrors.tuna.tsinghua.edu.cn trusty Release.gpg                    
命中 http://mirrors.tuna.tsinghua.edu.cn trusty Release                        
命中 http://mirrors.tuna.tsinghua.edu.cn trusty-updates/main Sources           
命中 http://mirrors.tuna.tsinghua.edu.cn trusty-updates/restricted Sources     
命中 http://mirrors.tuna.tsinghua.edu.cn trusty-updates/universe Sources       
命中 http://mirrors.tuna.tsinghua.edu.cn trusty-updates/multiverse Sources     
命中 http://archive.ubuntukylin.com:10006 xenial InRelease                     
命中 http://mirrors.tuna.tsinghua.edu.cn trusty-updates/main amd64 Packages    
命中 http://mirrors.tuna.tsinghua.edu.cn trusty-updates/restricted amd64 Packages
命中 http://mirrors.tuna.tsinghua.edu.cn trusty-updates/universe amd64 Packages
命中 http://mirrors.tuna.tsinghua.edu.cn trusty-updates/multiverse amd64 Packages
命中 http://mirrors.tuna.tsinghua.edu.cn trusty-updates/main i386 Packages     
命中 http://mirrors.tuna.tsinghua.edu.cn trusty-updates/restricted i386 Packages
命中 http://mirrors.tuna.tsinghua.edu.cn trusty-updates/universe i386 Packages 
命中 http://archive.ubuntukylin.com:10006 xenial/main amd64 Packages           
命中 http://archive.ubuntukylin.com:10006 xenial/main i386 Packages            
命中 http://mirrors.tuna.tsinghua.edu.cn trusty-updates/multiverse i386 Packages
命中 http://mirrors.tuna.tsinghua.edu.cn trusty-updates/main Translation-en    
命中 http://mirrors.tuna.tsinghua.edu.cn trusty-updates/multiverse Translation-en
命中 http://mirrors.tuna.tsinghua.edu.cn trusty-updates/restricted Translation-en
命中 http://mirrors.tuna.tsinghua.edu.cn trusty-updates/universe Translation-en
忽略 http://dl.google.com stable InRelease                                     
命中 http://archive.ubuntukylin.com:10006 xenial/main Translation-en           
命中 http://mirrors.tuna.tsinghua.edu.cn trusty-backports/main Sources         
命中 http://mirrors.tuna.tsinghua.edu.cn trusty-backports/restricted Sources   
命中 http://mirrors.tuna.tsinghua.edu.cn trusty-backports/universe Sources     
命中 http://mirrors.tuna.tsinghua.edu.cn trusty-backports/multiverse Sources   
命中 http://mirrors.tuna.tsinghua.edu.cn trusty-backports/main amd64 Packages  
命中 http://dl.google.com stable Release.gpg                                   
命中 http://mirrors.tuna.tsinghua.edu.cn trusty-backports/restricted amd64 Packages
命中 http://mirrors.tuna.tsinghua.edu.cn trusty-backports/universe amd64 Packages
命中 http://mirrors.tuna.tsinghua.edu.cn trusty-backports/multiverse amd64 Packages
命中 http://mirrors.tuna.tsinghua.edu.cn trusty-backports/main i386 Packages   
命中 http://linux.teamviewer.com stable InRelease                              
命中 http://mirrors.tuna.tsinghua.edu.cn trusty-backports/restricted i386 Packages
命中 http://mirrors.tuna.tsinghua.edu.cn trusty-backports/universe i386 Packages
命中 http://mirrors.tuna.tsinghua.edu.cn trusty-backports/multiverse i386 Packages
命中 http://dl.google.com stable Release                                       
命中 http://linux.teamviewer.com preview InRelease                             
命中 http://mirrors.tuna.tsinghua.edu.cn trusty-backports/main Translation-en  
命中 http://mirrors.tuna.tsinghua.edu.cn trusty-backports/multiverse Translation-en
命中 http://linux.teamviewer.com stable/main amd64 Packages                    
命中 http://mirrors.tuna.tsinghua.edu.cn trusty-backports/restricted Translation-en
命中 http://mirrors.tuna.tsinghua.edu.cn trusty-backports/universe Translation-en
命中 http://mirrors.tuna.tsinghua.edu.cn trusty-security/main Sources          
命中 http://mirrors.tuna.tsinghua.edu.cn trusty-security/restricted Sources    
命中 http://mirrors.tuna.tsinghua.edu.cn trusty-security/universe Sources      
命中 http://mirrors.tuna.tsinghua.edu.cn trusty-security/multiverse Sources    
命中 http://mirrors.tuna.tsinghua.edu.cn trusty-security/main amd64 Packages   
命中 http://mirrors.tuna.tsinghua.edu.cn trusty-security/restricted amd64 Packages
命中 http://linux.teamviewer.com stable/main i386 Packages                     
命中 http://mirrors.tuna.tsinghua.edu.cn trusty-security/universe amd64 Packages
命中 http://mirrors.tuna.tsinghua.edu.cn trusty-security/multiverse amd64 Packages
命中 http://dl.google.com stable/main amd64 Packages                           
命中 http://mirrors.tuna.tsinghua.edu.cn trusty-security/main i386 Packages    
命中 http://mirrors.tuna.tsinghua.edu.cn trusty-security/restricted i386 Packages
命中 http://mirrors.tuna.tsinghua.edu.cn trusty-security/universe i386 Packages
命中 http://mirrors.tuna.tsinghua.edu.cn trusty-security/multiverse i386 Packages
命中 http://mirrors.tuna.tsinghua.edu.cn trusty-security/main Translation-en   
命中 http://mirrors.tuna.tsinghua.edu.cn trusty-security/multiverse Translation-en
忽略 http://ppa.launchpad.net trusty InRelease                                 
命中 http://mirrors.tuna.tsinghua.edu.cn trusty-security/restricted Translation-en
命中 http://mirrors.tuna.tsinghua.edu.cn trusty-security/universe Translation-en
忽略 http://extras.ubuntu.com trusty InRelease                                 
命中 http://mirrors.tuna.tsinghua.edu.cn trusty/main Sources                   
命中 http://mirrors.tuna.tsinghua.edu.cn trusty/restricted Sources             
命中 http://mirrors.tuna.tsinghua.edu.cn trusty/universe Sources               
命中 http://mirrors.tuna.tsinghua.edu.cn trusty/multiverse Sources             
命中 http://mirrors.tuna.tsinghua.edu.cn trusty/main amd64 Packages            
命中 http://mirrors.tuna.tsinghua.edu.cn trusty/restricted amd64 Packages      
命中 http://mirrors.tuna.tsinghua.edu.cn trusty/universe amd64 Packages        
命中 http://mirrors.tuna.tsinghua.edu.cn trusty/multiverse amd64 Packages      
命中 http://mirrors.tuna.tsinghua.edu.cn trusty/main i386 Packages             
命中 http://mirrors.tuna.tsinghua.edu.cn trusty/restricted i386 Packages       
命中 http://mirrors.tuna.tsinghua.edu.cn trusty/universe i386 Packages         
命中 http://mirrors.tuna.tsinghua.edu.cn trusty/multiverse i386 Packages       
命中 http://mirrors.tuna.tsinghua.edu.cn trusty/main Translation-zh_CN         
命中 http://mirrors.tuna.tsinghua.edu.cn trusty/main Translation-en            
命中 http://mirrors.tuna.tsinghua.edu.cn trusty/multiverse Translation-zh_CN   
命中 http://mirrors.tuna.tsinghua.edu.cn trusty/multiverse Translation-en      
命中 http://mirrors.tuna.tsinghua.edu.cn trusty/restricted Translation-zh_CN   
命中 http://mirrors.tuna.tsinghua.edu.cn trusty/restricted Translation-en      
命中 http://mirrors.tuna.tsinghua.edu.cn trusty/universe Translation-zh_CN     
命中 http://mirrors.tuna.tsinghua.edu.cn trusty/universe Translation-en        
命中 http://extras.ubuntu.com trusty Release.gpg                               
命中 http://packages.microsoft.com stable InRelease                            
忽略 http://mirrors.tuna.tsinghua.edu.cn trusty/main Translation-zh            
忽略 http://mirrors.tuna.tsinghua.edu.cn trusty/multiverse Translation-zh      
忽略 http://mirrors.tuna.tsinghua.edu.cn trusty/restricted Translation-zh      
忽略 http://mirrors.tuna.tsinghua.edu.cn trusty/universe Translation-zh        
命中 http://ppa.launchpad.net trusty InRelease                                 
命中 http://extras.ubuntu.com trusty Release                                   
命中 http://extras.ubuntu.com trusty/main Sources                              
忽略 http://dl.google.com stable/main Translation-zh_CN                        
命中 http://ppa.launchpad.net trusty InRelease                                 
命中 http://extras.ubuntu.com trusty/main amd64 Packages                       
忽略 http://dl.google.com stable/main Translation-zh                           
忽略 http://dl.google.com stable/main Translation-en                           
命中 http://linux.teamviewer.com preview/main amd64 Packages                   
命中 http://linux.teamviewer.com preview/main i386 Packages                    
命中 http://extras.ubuntu.com trusty/main i386 Packages                        
命中 http://ppa.launchpad.net trusty Release.gpg                               
命中 http://ppa.launchpad.net trusty/main amd64 Packages                       
命中 http://ppa.launchpad.net trusty/main i386 Packages                        
忽略 http://packages.microsoft.com stable/main Translation-zh_CN               
忽略 http://packages.microsoft.com stable/main Translation-zh                  
命中 http://ppa.launchpad.net trusty/main Translation-en                       
忽略 http://packages.microsoft.com stable/main Translation-en                  
命中 http://ppa.launchpad.net trusty/main amd64 Packages                       
命中 http://ppa.launchpad.net trusty/main i386 Packages                        
命中 http://packages.microsoft.com stable/main amd64 Packages                  
命中 http://ppa.launchpad.net trusty/main Translation-en                       
忽略 http://extras.ubuntu.com trusty/main Translation-zh_CN                    
忽略 http://extras.ubuntu.com trusty/main Translation-zh                       
命中 http://ppa.launchpad.net trusty Release                                   
忽略 http://extras.ubuntu.com trusty/main Translation-en                       
命中 http://ppa.launchpad.net trusty/main amd64 Packages                       
命中 http://ppa.launchpad.net trusty/main i386 Packages                        
命中 http://ppa.launchpad.net trusty/main Translation-en                       
忽略 http://linux.teamviewer.com stable/main Translation-zh_CN                 
忽略 http://linux.teamviewer.com stable/main Translation-zh                    
忽略 http://linux.teamviewer.com stable/main Translation-en                    
忽略 http://linux.teamviewer.com preview/main Translation-zh_CN                
忽略 http://linux.teamviewer.com preview/main Translation-zh                   
忽略 http://linux.teamviewer.com preview/main Translation-en                   
正在读取软件包列表... 完成                                                     
W: Ignoring Provides line with DepCompareOp for package libjpeg62
W: 您可能需要运行 apt-get update 来解决这些问题
installing libs...
(正在读取数据库 ... 系统当前共安装有 215365 个文件和目录。)
正准备解包 .../libs/libgif4_4.1.6-11_i386.deb  ...
正在将 libgif4:i386 (4.1.6-11) 解包到 (4.1.6-11) 上 ...
dpkg: 关于含有 libgnutls-deb0-28:i386 的 .../libgnutls-deb0-28_3.3.20-1_i386.deb：
 libgnutls-deb0-28 冲突于 libhogweed2
  libhogweed2:amd64 (版本为 2.7.1-1ubuntu0.2)已存在并且 已安装。

dpkg: 处理归档 ./libs/libgnutls-deb0-28_3.3.20-1_i386.deb (--install)时出错：
 软件包相互冲突 - 将不安装 libgnutls-deb0-28:i386
正准备解包 .../libgnutls26_2.12.23-18_i386.deb  ...
正在反配置 libgnutls26:amd64 (2.12.23-12ubuntu2.8) ...
正在将 libgnutls26:i386 (2.12.23-18) 解包到 (2.12.23-12ubuntu2.8) 上 ...
正在选中未选择的软件包 libgstreamer-plugins-base0.10-0:i386。
正准备解包 .../libgstreamer-plugins-base0.10-0_0.10.36-2_i386.deb  ...
正在反配置 libgstreamer-plugins-base0.10-0:amd64 (0.10.36-1.1ubuntu2) ...
正在解包 libgstreamer-plugins-base0.10-0:i386 (0.10.36-2) ...
正在选中未选择的软件包 libgstreamer0.10-0:i386。
正准备解包 .../libgstreamer0.10-0_0.10.36-1.5_i386.deb  ...
正在反配置 libgstreamer0.10-0:amd64 (0.10.36-1.2ubuntu3) ...
正在解包 libgstreamer0.10-0:i386 (0.10.36-1.5) ...
正准备解包 .../libjpeg62-turbo_1.5.1-2_i386.deb  ...
正在将 libjpeg62-turbo:i386 (1:1.5.1-2) 解包到 (1:1.5.1-2) 上 ...
正准备解包 .../libpng16-16_1.6.34-1_i386.deb  ...
正在将 libpng16-16:i386 (1.6.34-1) 解包到 (1.6.34-1) 上 ...
正准备解包 .../libreadline7_7.0-1_i386.deb  ...
正在将 libreadline7:i386 (7.0-1) 解包到 (7.0-1) 上 ...
正准备解包 ./libs/udis86_1.72-2_i386.deb  ...
正在将 udis86 (1.72-2) 解包到 (1.72-2) 上 ...
正在设置 libgif4:i386 (4.1.6-11) ...
dpkg: 处理软件包 libgnutls26:i386 (--install)时出错：
 现在尚不能配置软件包 libgnutls26:i386 2.12.23-18，因为 libgnutls26:amd64 处于一个不同的版本(2.12.23-12ubuntu2.8)
dpkg: 处理软件包 libgnutls26:amd64 (--install)时出错：
 现在尚不能配置软件包 libgnutls26:amd64 2.12.23-12ubuntu2.8，因为 libgnutls26:i386 处于一个不同的版本(2.12.23-18)
dpkg: 处理软件包 libgstreamer-plugins-base0.10-0:i386 (--install)时出错：
 现在尚不能配置软件包 libgstreamer-plugins-base0.10-0:i386 0.10.36-2，因为 libgstreamer-plugins-base0.10-0:amd64 处于一个不同的版本(0.10.36-1.1ubuntu2)
dpkg: 处理软件包 libgstreamer-plugins-base0.10-0:amd64 (--install)时出错：
 现在尚不能配置软件包 libgstreamer-plugins-base0.10-0:amd64 0.10.36-1.1ubuntu2，因为 libgstreamer-plugins-base0.10-0:i386 处于一个不同的版本(0.10.36-2)
dpkg: 处理软件包 libgstreamer0.10-0:i386 (--install)时出错：
 现在尚不能配置软件包 libgstreamer0.10-0:i386 0.10.36-1.5，因为 libgstreamer0.10-0:amd64 处于一个不同的版本(0.10.36-1.2ubuntu3)
dpkg: 处理软件包 libgstreamer0.10-0:amd64 (--install)时出错：
 现在尚不能配置软件包 libgstreamer0.10-0:amd64 0.10.36-1.2ubuntu3，因为 libgstreamer0.10-0:i386 处于一个不同的版本(0.10.36-1.5)
正在设置 libjpeg62-turbo:i386 (1:1.5.1-2) ...
正在设置 libpng16-16:i386 (1.6.34-1) ...
正在设置 libreadline7:i386 (7.0-1) ...
正在设置 udis86 (1.72-2) ...
正在处理用于 libc-bin (2.19-0ubuntu6.9) 的触发器 ...
正在处理用于 doc-base (0.10.5) 的触发器 ...
Processing 1 changed doc-base file...
在处理时有错误发生：
 ./libs/libgnutls-deb0-28_3.3.20-1_i386.deb
 libgnutls26:i386
 libgnutls26:amd64
 libgstreamer-plugins-base0.10-0:i386
 libgstreamer-plugins-base0.10-0:amd64
 libgstreamer0.10-0:i386
 libgstreamer0.10-0:amd64
正在读取软件包列表... 完成
正在分析软件包的依赖关系树       
正在读取状态信息... 完成       
正在更正依赖关系... 完成
下列软件包是自动安装的并且现在不需要了：
  dh-apparmor diffstat g++ g++-4.8 gcc-4.8-base:i386 gettext intltool-debian
  kde-l10n-engb kde-l10n-zhcn libalgorithm-diff-perl libalgorithm-diff-xs-perl
  libalgorithm-merge-perl libapt-pkg-perl libarchive-zip-perl libasound2:i386
  libasound2-plugins:i386 libasprintf-dev libasyncns0:i386 libatk1.0-0:i386
  libautodie-perl libavahi-client3:i386 libavahi-common-data:i386
  libavahi-common3:i386 libbsd0:i386 libc6-dev:i386 libcairo2:i386
  libclass-accessor-perl libclone-perl libdatrie1:i386 libdpkg-perl
  libdrm-amdgpu1:i386 libdrm-intel1:i386 libdrm-nouveau2:i386
  libdrm-radeon1:i386 libedit2:i386 libelf1:i386 libemail-valid-perl
  libexpat1:i386 libffi6:i386 libfile-fcntllock-perl libflac8:i386
  libfontconfig1:i386 libfreetype6:i386 libgcrypt11:i386
  libgdk-pixbuf2.0-0:i386 libgettextpo-dev libgl1-mesa-dri-lts-xenial:i386
  libglib2.0-0:i386 libgpg-error0:i386 libgraphite2-3:i386
  libgssapi-krb5-2:i386 libharfbuzz0b:i386 libice6:i386 libio-pty-perl
  libio-string-perl libipc-run-perl libipc-system-simple-perl
  libjack-jackd2-0:i386 libjasper1:i386 libjbig0:i386 libjpeg-turbo8:i386
  libjpeg8:i386 libk5crypto3:i386 libkeyutils1:i386 libkrb5-3:i386
  libkrb5support0:i386 liblist-moreutils-perl libllvm3.8v4:i386
  libmail-sendmail-perl libnet-dns-perl libnet-domain-tld-perl libnet-ip-perl
  libogg0:i386 libp11-kit0:i386 libpango-1.0-0:i386 libpangocairo-1.0-0:i386
  libpangoft2-1.0-0:i386 libparse-debianchangelog-perl libpciaccess0:i386
  libperlio-gzip-perl libpixman-1-0:i386 libpulse0:i386 libsamplerate0:i386
  libsm6:i386 libsndfile1:i386 libspeexdsp1:i386 libstdc++6:i386
  libsub-identify-perl libsub-name-perl libsys-hostname-long-perl
  libtasn1-6:i386 libtext-levenshtein-perl libthai0:i386 libtiff5:i386
  libtxc-dxtn-s2tc0:i386 libvorbis0a:i386 libvorbisenc2:i386 libwrap0:i386
  libx11-6:i386 libxau6:i386 libxcb-render0:i386 libxcb-shm0:i386 libxcb1:i386
  libxcomposite1:i386 libxcursor1:i386 libxdamage1:i386 libxdmcp6:i386
  libxext6:i386 libxfixes3:i386 libxi6:i386 libxinerama1:i386 libxrandr2:i386
  libxrender1:i386 libxt6:i386 linux-libc-dev:i386 patchutils po-debconf
  t1utils
Use 'apt-get autoremove' to remove them.
下列软件包将被【卸载】：
  deepin-wine-helper:i386 deepin-wine-plugin:i386 deepin-wine-plugin-virtual
  libcups2:i386 libgnutls26:i386 libgstreamer-plugins-base0.10-0:i386
  libgstreamer0.10-0:i386 libgtk2.0-0:i386
升级了 0 个软件包，新安装了 0 个软件包，要卸载 8 个软件包，有 354 个软件包未被升级。
有 6 个软件包没有被完全安装或卸载。
解压缩后将会空出 15.0 MB 的空间。
(正在读取数据库 ... 系统当前共安装有 215498 个文件和目录。)
正在卸载 deepin-wine-helper (1.1deepin9) ...
正在卸载 deepin-wine-plugin-virtual (1.0deepin0) ...
正在卸载 deepin-wine-plugin (1.0deepin2) ...
正在卸载 libgtk2.0-0:i386 (2.24.23-0ubuntu1.4) ...
正在卸载 libcups2:i386 (1.7.2-0ubuntu1.10) ...
正在卸载 libgnutls26:i386 (2.12.23-18) ...
正在卸载 libgstreamer-plugins-base0.10-0:i386 (0.10.36-2) ...
正在卸载 libgstreamer0.10-0:i386 (0.10.36-1.5) ...
正在处理用于 libc-bin (2.19-0ubuntu6.9) 的触发器 ...
正在设置 libgnutls26:amd64 (2.12.23-12ubuntu2.8) ...
正在设置 libgstreamer0.10-0:amd64 (0.10.36-1.2ubuntu3) ...
正在设置 libgstreamer-plugins-base0.10-0:amd64 (0.10.36-1.1ubuntu2) ...
正在处理用于 libc-bin (2.19-0ubuntu6.9) 的触发器 ...
W: Ignoring Provides line with DepCompareOp for package libjpeg62
W: 您可能需要运行 apt-get update 来解决这些问题
installing deepin-wine...
(正在读取数据库 ... 系统当前共安装有 215322 个文件和目录。)
正准备解包 .../1-deepin-fonts-wine_2.18-8~rc4_all.deb  ...
正在将 deepin-fonts-wine (2.18-8~rc4) 解包到 (2.18-8~rc4) 上 ...
dpkg-deb：错误：归档 ./deepin-wine/2.1-deepin-libwine_2.18-8~rc4_i386.deb 含有不合时宜的成员 control.tar.xz 于 control.tar.gz 之前，放弃操作
dpkg: 处理归档 ./deepin-wine/2.1-deepin-libwine_2.18-8~rc4_i386.deb (--install)时出错：
 子进程 dpkg-deb --control 返回了错误号 2
正在选中未选择的软件包 deepin-libwine-dbg:i386。
正准备解包 .../2.2-deepin-libwine-dbg_2.18-8~rc4_i386.deb  ...
正在解包 deepin-libwine-dbg:i386 (2.18-8~rc4) ...
正在选中未选择的软件包 deepin-libwine-dev:i386。
正准备解包 .../2.3-deepin-libwine-dev_2.18-8~rc4_i386.deb  ...
正在解包 deepin-libwine-dev:i386 (2.18-8~rc4) ...
正在选中未选择的软件包 deepin-wine32。
正准备解包 .../3.1-deepin-wine32_2.18-8~rc4_i386.deb  ...
正在解包 deepin-wine32 (2.18-8~rc4) ...
正在选中未选择的软件包 deepin-wine32-preloader。
正准备解包 .../3.2-deepin-wine32-preloader_2.18-8~rc4_i386.deb  ...
正在解包 deepin-wine32-preloader (2.18-8~rc4) ...
正在选中未选择的软件包 deepin-wine。
正准备解包 .../4-deepin-wine_2.18-8~rc4_all.deb  ...
正在解包 deepin-wine (2.18-8~rc4) ...
正在选中未选择的软件包 deepin-wine-binfmt。
正准备解包 .../5-deepin-wine-binfmt_2.18-8~rc4_all.deb  ...
正在解包 deepin-wine-binfmt (2.18-8~rc4) ...
正在选中未选择的软件包 deepin-wine-plugin。
正准备解包 .../6.1-deepin-wine-plugin_1.0deepin2_i386.deb  ...
正在解包 deepin-wine-plugin (1.0deepin2) ...
正在选中未选择的软件包 deepin-wine-plugin-virtual。
正准备解包 .../6.2-deepin-wine-plugin-virtual_1.0deepin0_all.deb  ...
正在解包 deepin-wine-plugin-virtual (1.0deepin0) ...
正在选中未选择的软件包 deepin-wine-helper。
正准备解包 .../7-deepin-wine-helper_1.1deepin9_i386.deb  ...
正在解包 deepin-wine-helper (1.1deepin9) ...
正准备解包 .../8-deepin-wine-uninstaller_0.1deepin2_i386.deb  ...
正在将 deepin-wine-uninstaller (0.1deepin2) 解包到 (0.1deepin2) 上 ...
正在设置 deepin-fonts-wine (2.18-8~rc4) ...
dpkg: 依赖关系问题使得 deepin-libwine-dbg:i386 的配置工作不能继续：
 deepin-libwine-dbg:i386 依赖于 deepin-libwine (= 2.18-8~rc4).

dpkg: 处理软件包 deepin-libwine-dbg:i386 (--install)时出错：
 依赖关系问题 - 仍未被配置
dpkg: 依赖关系问题使得 deepin-libwine-dev:i386 的配置工作不能继续：
 deepin-libwine-dev:i386 依赖于 deepin-libwine (= 2.18-8~rc4).

dpkg: 处理软件包 deepin-libwine-dev:i386 (--install)时出错：
 依赖关系问题 - 仍未被配置
dpkg: 依赖关系问题使得 deepin-wine32 的配置工作不能继续：
 deepin-wine32 依赖于 deepin-libwine (= 2.18-8~rc4).

dpkg: 处理软件包 deepin-wine32 (--install)时出错：
 依赖关系问题 - 仍未被配置
dpkg: 依赖关系问题使得 deepin-wine32-preloader 的配置工作不能继续：
 deepin-wine32-preloader 依赖于 deepin-wine32 (= 2.18-8~rc4)；然而：
  软件包 deepin-wine32 尚未配置。

dpkg: 处理软件包 deepin-wine32-preloader (--install)时出错：
 依赖关系问题 - 仍未被配置
dpkg: 依赖关系问题使得 deepin-wine 的配置工作不能继续：
 deepin-wine 依赖于 deepin-wine64 (>= 2.18-8~rc4) | deepin-wine32 (>= 2.18-8~rc4)；然而：
  未安装软件包 deepin-wine64。
  软件包 deepin-wine32 尚未配置。
 deepin-wine 依赖于 deepin-wine64 (<< 2.18-8~rc4.1~) | deepin-wine32 (<< 2.18-8~rc4.1~)；然而：
  未安装软件包 deepin-wine64。
  软件包 deepin-wine32 尚未配置。

dpkg: 处理软件包 deepin-wine (--install)时出错：
 依赖关系问题 - 仍未被配置
dpkg: 依赖关系问题使得 deepin-wine-binfmt 的配置工作不能继续：
 deepin-wine-binfmt 依赖于 deepin-wine；然而：
  软件包 deepin-wine 尚未配置。

dpkg: 处理软件包 deepin-wine-binfmt (--install)时出错：
 依赖关系问题 - 仍未被配置
dpkg: 依赖关系问题使得 deepin-wine-plugin 的配置工作不能继续：
 deepin-wine-plugin 依赖于 libgtk2.0-0；然而：
  未安装软件包 libgtk2.0-0:i386。

dpkg: 处理软件包 deepin-wine-plugin (--install)时出错：
 依赖关系问题 - 仍未被配置
dpkg: 依赖关系问题使得 deepin-wine-plugin-virtual 的配置工作不能继续：
 deepin-wine-plugin-virtual 依赖于 deepin-wine-plugin；然而：
  软件包 deepin-wine-plugin 尚未配置。

dpkg: 处理软件包 deepin-wine-plugin-virtual (--install)时出错：
 依赖关系问题 - 仍未被配置
dpkg: 依赖关系问题使得 deepin-wine-helper 的配置工作不能继续：
 deepin-wine-helper 依赖于 deepin-wine-plugin-virtual；然而：
  软件包 deepin-wine-plugin-virtual 尚未配置。

dpkg: 处理软件包 deepin-wine-helper (--install)时出错：
 依赖关系问题 - 仍未被配置
正在设置 deepin-wine-uninstaller (0.1deepin2) ...
正在处理用于 man-db (2.6.7.1-1ubuntu1) 的触发器 ...
在处理时有错误发生：
 ./deepin-wine/2.1-deepin-libwine_2.18-8~rc4_i386.deb
 deepin-libwine-dbg:i386
 deepin-libwine-dev:i386
 deepin-wine32
 deepin-wine32-preloader
 deepin-wine
 deepin-wine-binfmt
 deepin-wine-plugin
 deepin-wine-plugin-virtual
 deepin-wine-helper
正在读取软件包列表... 完成
正在分析软件包的依赖关系树       
正在读取状态信息... 完成       
正在更正依赖关系... 完成
下列软件包是自动安装的并且现在不需要了：
  dh-apparmor diffstat g++ g++-4.8 gettext intltool-debian kde-l10n-engb
  kde-l10n-zhcn libalgorithm-diff-perl libalgorithm-diff-xs-perl
  libalgorithm-merge-perl libapt-pkg-perl libarchive-zip-perl libasprintf-dev
  libautodie-perl libc6-dev:i386 libclass-accessor-perl libclone-perl
  libdpkg-perl libdrm-amdgpu1:i386 libdrm-intel1:i386 libdrm-nouveau2:i386
  libdrm-radeon1:i386 libedit2:i386 libelf1:i386 libemail-valid-perl
  libfile-fcntllock-perl libgettextpo-dev libgl1-mesa-dri-lts-xenial:i386
  libio-pty-perl libio-string-perl libipc-run-perl libipc-system-simple-perl
  liblist-moreutils-perl libllvm3.8v4:i386 libmail-sendmail-perl
  libnet-dns-perl libnet-domain-tld-perl libnet-ip-perl
  libparse-debianchangelog-perl libpciaccess0:i386 libperlio-gzip-perl
  libsub-identify-perl libsub-name-perl libsys-hostname-long-perl
  libtext-levenshtein-perl libtxc-dxtn-s2tc0:i386 linux-libc-dev:i386
  patchutils po-debconf t1utils
Use 'apt-get autoremove' to remove them.
将会安装下列额外的软件包：
  libcups2:i386 libgnutls26:i386 libgtk2.0-0:i386
建议安装的软件包：
  gnutls-bin:i386 librsvg2-common:i386 gvfs:i386
下列软件包将被【卸载】：
  deepin-libwine-dbg:i386 deepin-libwine-dev:i386 deepin-wine
  deepin-wine-binfmt deepin-wine32:i386 deepin-wine32-preloader:i386
下列【新】软件包将被安装：
  libcups2:i386 libgnutls26:i386 libgtk2.0-0:i386
升级了 0 个软件包，新安装了 3 个软件包，要卸载 6 个软件包，有 354 个软件包未被升级。
有 9 个软件包没有被完全安装或卸载。
需要下载 0 B/2,248 kB 的软件包。
解压缩后将会空出 26.5 MB 的空间。
(正在读取数据库 ... 系统当前共安装有 216501 个文件和目录。)
正在卸载 deepin-libwine-dbg:i386 (2.18-8~rc4) ...
正在卸载 deepin-libwine-dev:i386 (2.18-8~rc4) ...
正在卸载 deepin-wine-binfmt (2.18-8~rc4) ...
正在卸载 deepin-wine (2.18-8~rc4) ...
正在卸载 deepin-wine32-preloader (2.18-8~rc4) ...
正在卸载 deepin-wine32 (2.18-8~rc4) ...
正在处理用于 man-db (2.6.7.1-1ubuntu1) 的触发器 ...
正在选中未选择的软件包 libgnutls26:i386。
(正在读取数据库 ... 系统当前共安装有 215336 个文件和目录。)
正准备解包 .../libgnutls26_2.12.23-12ubuntu2.8_i386.deb  ...
正在解包 libgnutls26:i386 (2.12.23-12ubuntu2.8) ...
dpkg：警告：由于开启了 --force 选项，以下问题被忽略：
dpkg：警告：尝试覆盖共享的 '/usr/share/doc/libgnutls26/changelog.Debian.gz', 它与软件包 libgnutls26:i386 中的其他实例不同
正在选中未选择的软件包 libcups2:i386。
正准备解包 .../libcups2_1.7.2-0ubuntu1.10_i386.deb  ...
正在解包 libcups2:i386 (1.7.2-0ubuntu1.10) ...
正在选中未选择的软件包 libgtk2.0-0:i386。
正准备解包 .../libgtk2.0-0_2.24.23-0ubuntu1.4_i386.deb  ...
正在解包 libgtk2.0-0:i386 (2.24.23-0ubuntu1.4) ...
正在设置 libgnutls26:i386 (2.12.23-12ubuntu2.8) ...
正在设置 libcups2:i386 (1.7.2-0ubuntu1.10) ...
正在设置 libgtk2.0-0:i386 (2.24.23-0ubuntu1.4) ...
正在设置 deepin-wine-plugin (1.0deepin2) ...
正在设置 deepin-wine-plugin-virtual (1.0deepin0) ...
正在设置 deepin-wine-helper (1.1deepin9) ...
正在处理用于 libc-bin (2.19-0ubuntu6.9) 的触发器 ...
W: Ignoring Provides line with DepCompareOp for package libjpeg62
W: 您可能需要运行 apt-get update 来解决这些问题
E: 未知的命令行选项“y” [来自 -y]
done.
xwj@LAB:/media/xwj/File/software/Deepin-Apps-Installation/deepin-wine$ sudo dpkg -i 2.1-deepin-libwine_2.18-8~rc4_i386.deb 
dpkg-deb：错误：归档 2.1-deepin-libwine_2.18-8~rc4_i386.deb 含有不合时宜的成员 control.tar.xz 于 control.tar.gz 之前，放弃操作
dpkg: 处理归档 2.1-deepin-libwine_2.18-8~rc4_i386.deb (--install)时出错：
 子进程 dpkg-deb --control 返回了错误号 2
在处理时有错误发生：
 2.1-deepin-libwine_2.18-8~rc4_i386.deb`

用软件管理器安装2.1-deepin-libwine_2.18-8~rc4_i386.deb提示libc6（>=2.23）不满足，请问这该怎么办？

**Comment by Jactor-Sue** [comment]
我用虚拟机安装了一个Ubuntu14.04试了一下，确实安装不了，这个是由于deepin-wine 2.18版本是在Ubuntu16版本下开发和使用的，所以不能支持14.04版本，很遗憾。

**Comment by xwjBupt** [comment]
好吧，不过还是感谢大佬的回复啦
